const {
  MONGO_CONNECTION_STRING,
  API_PORT,
  JWT_SECRET,
  CLOUDINARY_NAME,
  CLOUDINARY_KEY,
  CLOUDINARY_SECRET,
} = process.env;

module.exports = {
  MONGO_CONNECTION_STRING,
  API_PORT,
  JWT_SECRET,
  CLOUDINARY_NAME,
  CLOUDINARY_KEY,
  CLOUDINARY_SECRET,
};
